name: Publish shared-modules to npmjs
on:
  push:
      branches:
      - 'master'
      - 'develop'
      paths: 
        - "api/shared-modules/**"
        - ".github/workflows/publish-shared-modules-sdk-npmjs.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
            cd api/shared-modules
            jq -r '"PACKAGE_JSON=\(.version)"' package.json >> $GITHUB_ENV 
      - name: Stable version
        if: ${{ !contains(env.PACKAGE_JSON, 'alpha') }}
        run: |
          cd api/shared-modules
          npm ci
          npm run build
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Pre-release version
        if: ${{ contains(env.PACKAGE_JSON, 'alpha') }}
        run: |
          cd api/shared-modules
          npm ci
          npm run build
          npm publish --tag next --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}